@startuml SnakeGame
class Juego
class Jugador 
class Snake

class World
class Nivel
class Comida

class Habilidad
class Comer
class Avanzar

Juego "1" --* "1" Jugador
Jugador --|> Snake

Juego --* World
World --* Nivel
Nivel --* Comida

Comer --|> Habilidad
Avanzar --|> Habilidad
Snake --o Habilidad
 











@enduml